# Week20 - Dashboard Data Preparation

## Goal
Prepare clean and simple data files for the future Tableau dashboard.

## Why This Step Matters
This step organizes the key analysis results into dashboard-ready tables.
These files will be used in Tableau in the next stage.

In [1]:
import pandas as pd

In [2]:
clean_df = pd.read_csv('credit_risk_cleaned.csv')

In [4]:
clean_df['burden_group'] = pd.qcut(
    clean_df['loan_percent_income'],
    q=3,
    labels=['low_burden', 'medium_burden', 'high_burden']
)

In [5]:
dashboard_detail = clean_df[[
    'person_age',
    'person_income',
    'person_home_ownership',
    'person_emp_length',
    'loan_intent',
    'loan_grade',
    'loan_amnt',
    'loan_int_rate',
    'loan_status',
    'loan_percent_income',
    'cb_person_default_on_file',
    'cb_person_cred_hist_length',
    'burden_group'
]].copy()

dashboard_detail.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,burden_group
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,low_burden
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,high_burden
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,high_burden
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,high_burden
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2,high_burden

In [6]:
dashboard_detail.to_csv('dashboard_detail.csv', index=False)

In [7]:
dashboard_summary = pd.DataFrame({
    'metric': [
        'overall_default_rate',
        'average_income',
        'average_loan_amount',
        'average_interest_rate',
        'average_loan_percent_income'
    ],
    'value': [
        clean_df['loan_status'].mean(),
        clean_df['person_income'].mean(),
        clean_df['loan_amnt'].mean(),
        clean_df['loan_int_rate'].mean(),
        clean_df['loan_percent_income'].mean()
    ]
})

dashboard_summary

                        metric         value
0         overall_default_rate      0.218180
1               average_income  65878.480813
2          average_loan_amount   9588.018051
3        average_interest_rate     11.009470
4  average_loan_percent_income      0.170202

In [8]:
dashboard_summary.to_csv('dashboard_summary.csv', index=False)